### ISSUE TITLE
[BUG] Backup downloads result in 500 error

### ISSUE THREAD

**Issue by J0J0HA** [gnmyt/MCDash#120]
When downloading a Backup through the panel, I get a status code of 500 and the following response body from the api:
```json
{"message": "An internal error occurred"}
```

The minecraft logs say the following:
```
[16:06:55 WARN]: java.lang.reflect.InvocationTargetException
[16:06:55 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[16:06:55 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[16:06:55 WARN]:        at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.execute(DefaultHandler.java:79)
[16:06:55 WARN]:        at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.lambda$handle$0(DefaultHandler.java:67)
[16:06:55 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[16:06:55 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[16:06:55 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[16:06:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:06:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[16:06:55 WARN]: Caused by: java.lang.OutOfMemoryError: Required array size too large
[16:06:55 WARN]:        at java.base/java.nio.file.Files.readAllBytes(Files.java:3293)
[16:06:55 WARN]:        at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:2581)
[16:06:55 WARN]:        at MCDash-1.1.7.jar//de.gnmyt.mcdash.panel.routes.backups.BackupDownloadRoute.get(BackupDownloadRoute.java:38)
[16:06:55 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[16:06:55 WARN]:        ... 9 more
```

One special thing is that my backup files are around 27GB big. Maybe you server tries to load them into memory completely and fails because I only gave it 6GB RAM?

**Comment by Xitee1** [comment]
Duplicate of #107.
I'm having the same problem and always have to download the backup file via FTP.

**Comment by gnmyt** [comment]
Closing since it's a duplicate. The new versions will fix this issue. Feel free to try out beta releases in the meantime, I'll release the stable assets asap.
