### ISSUE TITLE
Warning idk how  to fix

### ISSUE THREAD

**Issue by tillbaxmann** [gnmyt/MCDash#138]
[21:17:46 WARN]: java.lang.reflect.InvocationTargetException
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[21:17:46 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.execute(DefaultHandler.java:79)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.lambda$handle$0(DefaultHandler.java:67)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:17:46 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:17:46 WARN]: Caused by: java.net.SocketTimeoutException: timeout
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.panel.routes.store.StoreRoute.get(StoreRoute.java:46)
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[21:17:46 WARN]: 	... 9 more
[21:17:46 WARN]: java.lang.reflect.InvocationTargetException
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[21:17:46 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.execute(DefaultHandler.java:79)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.lambda$handle$0(DefaultHandler.java:67)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:17:46 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:17:46 WARN]: Caused by: java.net.SocketTimeoutException: timeout
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.panel.routes.store.StoreRoute.get(StoreRoute.java:46)
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[21:17:46 WARN]: 	... 9 more
[21:17:46 WARN]: java.lang.reflect.InvocationTargetException
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[21:17:46 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.execute(DefaultHandler.java:79)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.api.handler.DefaultHandler.lambda$handle$0(DefaultHandler.java:67)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:17:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:17:46 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:17:46 WARN]: Caused by: java.net.SocketTimeoutException: timeout
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[21:17:46 WARN]: 	at MCDash-1.1.7.jar//de.gnmyt.mcdash.panel.routes.store.StoreRoute.get(StoreRoute.java:46)
[21:17:46 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[21:17:46 WARN]: 	... 9 more

**Comment by VoidableMoon884** [comment]
When did the error occur?
And does it still occur in the latest version?
