### ISSUE TITLE
Plugin incompatibility (At least it seems)

### ISSUE THREAD

**Issue by reality-exe** [gnmyt/MCDash#39]
It seems like ServerTap doesnt work with MCDash.

MCDash crashes when ServerTap is on the server

**Comment by gnmyt** [comment]
Hm, that's weird. Both plugins work fine on my system. Could you share some additional information like the console log, the server version and the OS you are running this on?

**Comment by reality-exe** [comment]
Here's what the console shows for me when loading em both at once (At least when MCDash fails)
```
- [Thu 06:24:54 ERROR Minecraft] Error occurred while enabling MinecraftDashboard v1.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bouncycastle/crypto/prng/RandomGenerator
    at MCDash-1.1.5.jar//org.apache.sshd.common.util.security.bouncycastle.BouncyCastleRandomFactory.create(BouncyCastleRandomFactory.java:43)
    at MCDash-1.1.5.jar//org.apache.sshd.common.util.security.bouncycastle.BouncyCastleRandomFactory.create(BouncyCastleRandomFactory.java:28)
    at MCDash-1.1.5.jar//org.apache.sshd.common.random.SingletonRandomFactory.<init>(SingletonRandomFactory.java:38)
    at MCDash-1.1.5.jar//org.apache.sshd.common.BaseBuilder.fillWithDefaultValues(BaseBuilder.java:166)
    at MCDash-1.1.5.jar//org.apache.sshd.server.ServerBuilder.fillWithDefaultValues(ServerBuilder.java:108)
    at MCDash-1.1.5.jar//org.apache.sshd.server.ServerBuilder.fillWithDefaultValues(ServerBuilder.java:58)
    at MCDash-1.1.5.jar//org.apache.sshd.common.BaseBuilder.build(BaseBuilder.java:273)
    at MCDash-1.1.5.jar//org.apache.sshd.server.ServerBuilder.build(ServerBuilder.java:151)
    at MCDash-1.1.5.jar//org.apache.sshd.server.ServerBuilder.build(ServerBuilder.java:58)
    at MCDash-1.1.5.jar//org.apache.sshd.common.BaseBuilder.build(BaseBuilder.java:297)
    at MCDash-1.1.5.jar//org.apache.sshd.server.SshServer.setUpDefaultServer(SshServer.java:442)
    at MCDash-1.1.5.jar//de.gnmyt.mcdash.api.controller.SSHController.start(SSHController.java:37)
    at MCDash-1.1.5.jar//de.gnmyt.mcdash.api.config.SSHManager.<init>(SSHManager.java:35)
    at MCDash-1.1.5.jar//de.gnmyt.mcdash.MinecraftDashboard.onEnable(MinecraftDashboard.java:34)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
```

I'm also running the server on a Docker Container [running with this image](https://hub.docker.com/r/marctv/minecraft-papermc-server).

Docker is running on a Hyper-V Ubuntu Server.

**Comment by gnmyt** [comment]
Have you enabled the ssh server in the ssh.yml configuration? (`plugins/MinecraftDashboard/ssh.yml`). If yes, can you try to disable it and restart the server?

**Comment by reality-exe** [comment]
Disabling that fixed it. Thanks lol dunno why i didnt try that after seeing SSHManager lmao
