### ISSUE TITLE
Unexpected Application Error!

### ISSUE THREAD

**Issue by SpyoChan** [gnmyt/MCDash#54]
**Unexpected Application Error!**

Cannot read properties of undefined (reading 'split')

```
TypeError: Cannot read properties of undefined (reading 'split')
    at o (http://dn16.falix.gg:58613/assets/index-bd775d73.js:250:14741)
    at vie (http://dn16.falix.gg:58613/assets/index-bd775d73.js:251:1076)
    at xC (http://dn16.falix.gg:58613/assets/index-bd775d73.js:38:19538)
    at X1 (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:3139)
    at aA (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:44830)
    at oA (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:39787)
    at XF (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:39715)
    at kg (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:39568)
    at lb (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:35933)
    at nA (http://dn16.falix.gg:58613/assets/index-bd775d73.js:40:34882)
```
showing this how i fix it

**Comment by gnmyt** [comment]
This should only happen if a user was already authenticated and the credentials specified in the local storage are incorrect. You can try the following to fix this issue. However, I will create a PR that completely fixes this problem:
1. Try logging in again. You can do this by navigating to `/login` . In your case, this should be <http://dn16.falix.gg:58613/login>
2. Reset your local storage. To do this, go to your Dev Tools (`CTRL` + `Shift` + `I`) and click `Application` > `Local Storage` > `Clear All`. You can find a more detailed description [here](https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/)
